compatibility_date = "2021-12-24"
type = "javascript"
name = "baseless-hello-world"
account_id = "b17e7ad4e6cad0fc022458ad0014bcc5"
workers_dev = true

# [secrets]
# DEMO_ALG_KEY
# DEMO_PUBLIC_KEY
# DEMO_PRIVATE_KEY