export class InvalidIdentityError extends Error { }
export class InvalidIdentityIdentificationError extends Error { }
export class InvalidIdentityChallengeError extends Error { }
export class IdentityNotFoundError extends Error { }
export class IdentityExistsError extends Error { }
export class IdentityCreateError extends Error { }
export class IdentityUpdateError extends Error { }
export class IdentityDeleteError extends Error { }
export class IdentityIdentificationNotFoundError extends Error { }
export class IdentityIdentificationCreateError extends Error { }
export class IdentityIdentificationUpdateError extends Error { }
export class IdentityIdentificationDeleteError extends Error { }
export class IdentityIdentificationExistsError extends Error { }
export class IdentityChallengeNotFoundError extends Error { }
export class IdentityChallengeExistsError extends Error { }
export class IdentityChallengeCreateError extends Error { }
export class IdentityChallengeUpdateError extends Error { }
export class IdentityChallengeDeleteError extends Error { }