export class InvalidAuthenticationStepError extends Error { }
export class InvalidAuthenticationStateAnonymous extends Error { }
export class InvalidAuthenticationStateIdentified extends Error { }
export class InvalidAuthenticationState extends Error { }
export class InvalidAuthenticationChallengeError extends Error { }
export class InvalidAuthenticationChoiceError extends Error { }
export class InvalidAuthenticationConditionalError extends Error { }
export class InvalidAuthenticationIdentificationError extends Error { }
export class InvalidAuthenticationSequenceError extends Error { }
export class InvalidAuthenticationResultDoneError extends Error { }
export class InvalidAuthenticationResultErrorError extends Error { }
export class InvalidAuthenticationResultRedirectError extends Error { }
export class InvalidAuthenticationResultStateError extends Error { }
export class InvalidAuthenticationResultEncryptedStateError extends Error { }
export class InvalidAuthenticationResultError extends Error { }
export class AuthenticationFlowDoneError extends Error { }
export class AuthenticationInvalidStepError extends Error { }
export class AuthenticationRateLimitedError extends Error { }
export class AuthenticationMissingChallengeError extends Error { }
export class AuthenticationChallengeFailedError extends Error { }
export class AuthenticationMissingIdentificationError extends Error { }
export class AuthenticationSendValidationCodeError extends Error { }
export class AuthenticationConfirmValidationCodeError extends Error { }