name: Test

on:
  push:
    branches:    
      - '*'

jobs:

  deno-test:
    name: Run Deno Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run test
        run: deno test --config=./deno.json --import-map=./import-map.json